In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv("atlantictrain.csv")

In [7]:
df.head()

,ID,Name,Date,Time,Event,Status,Latitude,Longitude,Maximum Wind,Minimum Pressure,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,AL011851,UNNAMED,18510625,0,,HU,28.0N,94.8W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,AL011851,UNNAMED,18510625,600,,HU,28.0N,95.4W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,AL011851,UNNAMED,18510625,1200,,HU,28.0N,96.0W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,AL011851,UNNAMED,18510625,1800,,HU,28.1N,96.5W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,AL011851,UNNAMED,18510625,2100,L,HU,28.2N,96.8W,80,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [8]:
df.columns

Index(['ID', 'Name', 'Date', 'Time', 'Event', 'Status', 'Latitude',
       'Longitude', 'Maximum Wind', 'Minimum Pressure', 'Low Wind NE',
       'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE',
       'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW',
       'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW'],
      dtype='object')

In [9]:
xtrain=df[[c for c in df if c not in ["Status"]]]
xtrain.columns

Index(['ID', 'Name', 'Date', 'Time', 'Event', 'Latitude', 'Longitude',
       'Maximum Wind', 'Minimum Pressure', 'Low Wind NE', 'Low Wind SE',
       'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE', 'Moderate Wind SE',
       'Moderate Wind SW', 'Moderate Wind NW', 'High Wind NE', 'High Wind SE',
       'High Wind SW', 'High Wind NW'],
      dtype='object')

In [10]:
ytrain=df[["Status"]]
ytrain.head()

  Status
0     HU
1     HU
2     HU
3     HU
4     HU

In [11]:
ytrain.columns

Index(['Status'], dtype='object')

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le

LabelEncoder()

In [13]:
df["Status"]=le.fit_transform(df["Status"])

In [14]:
df["Status"]

0        2
1        2
2        2
3        2
4        2
        ..
49100    1
49101    1
49102    1
49103    1
49104    1
Name: Status, Length: 49105, dtype: int32

In [15]:
df["Status"].value_counts()

7    17804
2    14537
6     9891
1     4798
3     1005
5      557
4      293
8      116
0      104
Name: Status, dtype: int64

In [16]:
df.corr(method="pearson")

,Date,Time,Status,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
Date,1.000000,0.001195,0.059272,-0.220613,0.723695,0.489625,0.489646,0.490028,0.489972,0.490979,0.490990,0.491214,0.491101,0.491380,0.491403,0.491459,0.491409
Time,0.001195,1.000000,-0.004677,-0.005017,0.022164,-0.003209,-0.002986,-0.003384,-0.003364,-0.003282,-0.003275,-0.003326,-0.003324,-0.003330,-0.003336,-0.003372,-0.003362
Status,0.059272,-0.004677,1.000000,-0.524354,-0.040449,-0.034705,-0.037054,-0.038578,-0.036013,-0.033448,-0.034031,-0.032957,-0.033163,-0.031579,-0.031336,-0.030477,-0.030902
Maximum Wind,-0.220613,-0.005017,-0.524354,1.000000,0.010246,-0.036039,-0.037226,-0.039726,-0.037769,-0.041661,-0.042496,-0.044822,-0.043316,-0.046199,-0.046834,-0.047913,-0.047090
Minimum Pressure,0.723695,0.022164,-0.040449,0.010246,1.000000,0.476048,0.476046,0.476488,0.476418,0.477528,0.477523,0.477764,0.477684,0.477978,0.478000,0.478064,0.478025
Low Wind NE,0.489625,-0.003209,-0.034705,-0.036039,0.476048,1.000000,0.998258,0.997356,0.998292,0.997890,0.997680,0.997424,0.997589,0.996833,0.996806,0.996706,0.996796
Low Wind SE,0.489646,-0.002986,-0.037054,-0.037226,0.476046,0.998258,1.000000,0.998366,0.997587,0.997599,0.997914,0.997399,0.997233,0.996758,0.996835,0.996680,0.996681
Low Wind SW,0.490028,-0.003384,-0.038578,-0.039726,0.476488,0.997356,0.998366,1.000000,0.998538,0.998051,0.998379,0.998373,0.998046,0.997490,0.997574,0.997505,0.997473
Low Wind NW,0.489972,-0.003364,-0.036013,-0.037769,0.476418,0.998292,0.997587,0.998538,1.000000,0.998192,0.997946,0.998049,0.998283,0.997487,0.997441,0.997378,0.997464
Moderate Wind NE,0.490979,-0.003282,-0.033448,-0.041661,0.477528,0.997890,0.997599,0.998051,0.998192,1.000000,0.999671,0.999488,0.999655,0.999475,0.999426,0.999322,0.999362
Moderate Wind SE,0.490990,-0.003275,-0.034031,-0.042496,0.477523,0.997680,0.997914,0.998379,0.997946,0.999671,1.000000,0.999626,0.999482,0.999381,0.999439,0.999325,0.999326
Moderate Wind SW,0.491214,-0.003326,-0.032957,-0.044822,0.477764,0.997424,0.997399,0.998373,0.998049,0.999488,0.999626,1.000000,0.999719,0.999622,0.999671,0.999660,0.999643
Moderate Wind NW,0.491101,-0.003324,-0.033163,-0.043316,0.477684,0.997589,0.997233,0.998046,0.998283,0.999655,0.999482,0.999719,1.000000,0.999608,0.999580,0.999571,0.999632
High Wind NE,0.491380,-0.003330,-0.031579,-0.046199,0.477978,0.996833,0.996758,0.997490,0.997487,0.999475,0.999381,0.999622,0.999608,1.000000,0.999931,0.999886,0.999901
High Wind SE,0.491403,-0.003336,-0.031336,-0.046834,0.478000,0.996806,0.996835,0.997574,0.997441,0.999426,0.999439,0.999671,0.999580,0.999931,1.000000,0.999919,0.999888
High Wind SW,0.491459,-0.003372,-0.030477,-0.047913,0.478064,0.996706,0.996680,0.997505,0.997378,0.999322,0.999325,0.999660,0.999571,0.999886,0.999919,1.000000,0.999944
High Wind NW,0.491409,-0.003362,-0.030902,-0.047090,0.478025,0.996796,0.996681,0.997473,0.997464,0.999362,0.999326,0.999643,0.999632,0.999901,0.999888,0.999944,1.000000

In [17]:
df.describe()

,Date,Time,Status,Maximum Wind,Minimum Pressure,Low Wind NE,Low Wind SE,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
count,4.910500e+04,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000,49105.000000
mean,1.949802e+07,910.125975,4.597210,52.005091,-251.406496,-868.671031,-869.315772,-872.676428,-871.409245,-875.570940,-875.765319,-876.682028,-876.323205,-877.564321,-877.655045,-877.923552,-877.786295
std,4.461850e+05,671.043363,2.424731,27.681902,964.313907,353.299666,351.548910,342.153768,345.628984,333.651396,333.133376,330.526085,331.535176,328.027275,327.774794,327.021430,327.408253
min,1.851062e+07,0.000000,0.000000,-99.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000
25%,1.911110e+07,600.000000,2.000000,35.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000
50%,1.956093e+07,1200.000000,6.000000,45.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000
75%,1.989081e+07,1800.000000,7.000000,70.000000,990.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000
max,2.015111e+07,2330.000000,8.000000,165.000000,1024.000000,710.000000,600.000000,640.000000,530.000000,360.000000,300.000000,330.000000,360.000000,180.000000,250.000000,150.000000,180.000000

In [18]:
df.min()

ID                             AL011851
Name                                AMY
Date                           18510625
Time                                  0
Event
Status                                0
Latitude                          10.0N
Longitude                          0.0W
Maximum Wind                        -99
Minimum Pressure                   -999
Low Wind NE                        -999
Low Wind SE                        -999
Low Wind SW                        -999
Low Wind NW                        -999
Moderate Wind NE                   -999
Moderate Wind SE                   -999
Moderate Wind SW                   -999
Moderate Wind NW                   -999
High Wind NE                       -999
High Wind SE                       -999
High Wind SW                       -999
High Wind NW                       -999
dtype: object

In [19]:
df.isnull().sum()

ID                  0
Name                0
Date                0
Time                0
Event               0
Status              0
Latitude            0
Longitude           0
Maximum Wind        0
Minimum Pressure    0
Low Wind NE         0
Low Wind SE         0
Low Wind SW         0
Low Wind NW         0
Moderate Wind NE    0
Moderate Wind SE    0
Moderate Wind SW    0
Moderate Wind NW    0
High Wind NE        0
High Wind SE        0
High Wind SW        0
High Wind NW        0
dtype: int64

In [20]:
dftest=pd.read_csv("pacifictest.csv")

In [21]:
dftest.columns

Index(['ID', 'Name', 'Date', 'Time', 'Event', 'Status', 'Latitude',
       'Longitude', 'Maximum Wind', 'Minimum Pressure', 'Low Wind NE',
       'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE',
       'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW',
       'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW'],
      dtype='object')

In [22]:
dftest["Status"]=le.fit_transform(dftest["Status"])

In [23]:
xtest=dftest[[c for c in dftest if c not in ["Status"]]]
xtest

,ID,Name,Date,Time,Event,Latitude,Longitude,Maximum Wind,Minimum Pressure,Low Wind NE,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,EP011949,UNNAMED,19490611,0,,20.2N,106.3W,45,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,EP011949,UNNAMED,19490611,600,,20.2N,106.4W,45,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,EP011949,UNNAMED,19490611,1200,,20.2N,106.7W,45,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,EP011949,UNNAMED,19490611,1800,,20.3N,107.7W,45,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,EP011949,UNNAMED,19490612,0,,20.4N,108.6W,45,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26132,EP222015,SANDRA,20151128,1200,,21.7N,109.0W,35,1002,60,...,0,0,0,0,0,0,0,0,0,0
26133,EP222015,SANDRA,20151128,1800,,22.4N,108.7W,30,1007,0,...,0,0,0,0,0,0,0,0,0,0
26134,EP222015,SANDRA,20151129,0,,23.1N,108.3W,30,1008,0,...,0,0,0,0,0,0,0,0,0,0
26135,EP222015,SANDRA,20151129,600,,23.5N,107.9W,25,1009,0,...,0,0,0,0,0,0,0,0,0,0
26136,EP222015,SANDRA,20151129,1200,,24.2N,107.7W,20,1010,0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
ytest=dftest[["Status"]]
ytest.head()

   Status
0      11
1      11
2      11
3      11
4      11

In [25]:
ytest.shape

(26137, 1)

In [26]:
dftest["Status"].value_counts()

11    10076
10     6965
3      6765
5      1828
0       217
1       152
2       110
8         7
9         6
6         6
7         4
4         1
Name: Status, dtype: int64

In [27]:
from sklearn.tree import DecisionTreeClassifier

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49105 entries, 0 to 49104
Data columns (total 22 columns):
ID                  49105 non-null object
Name                49105 non-null object
Date                49105 non-null int64
Time                49105 non-null int64
Event               49105 non-null object
Status              49105 non-null int32
Latitude            49105 non-null object
Longitude           49105 non-null object
Maximum Wind        49105 non-null int64
Minimum Pressure    49105 non-null int64
Low Wind NE         49105 non-null int64
Low Wind SE         49105 non-null int64
Low Wind SW         49105 non-null int64
Low Wind NW         49105 non-null int64
Moderate Wind NE    49105 non-null int64
Moderate Wind SE    49105 non-null int64
Moderate Wind SW    49105 non-null int64
Moderate Wind NW    49105 non-null int64
High Wind NE        49105 non-null int64
High Wind SE        49105 non-null int64
High Wind SW        49105 non-null int64
High Wind NW        49105 non-null int64
dtypes: int32(1), int64(16), object(5)
memory usage: 8.1+ MB

In [29]:
xtrain.head()

,ID,Name,Date,Time,Event,Latitude,Longitude,Maximum Wind,Minimum Pressure,Low Wind NE,...,Low Wind SW,Low Wind NW,Moderate Wind NE,Moderate Wind SE,Moderate Wind SW,Moderate Wind NW,High Wind NE,High Wind SE,High Wind SW,High Wind NW
0,AL011851,UNNAMED,18510625,0,,28.0N,94.8W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
1,AL011851,UNNAMED,18510625,600,,28.0N,95.4W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
2,AL011851,UNNAMED,18510625,1200,,28.0N,96.0W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
3,AL011851,UNNAMED,18510625,1800,,28.1N,96.5W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999
4,AL011851,UNNAMED,18510625,2100,L,28.2N,96.8W,80,-999,-999,...,-999,-999,-999,-999,-999,-999,-999,-999,-999,-999

In [30]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit_transform(xtrain)

ValueError: bad input shape (49105, 21)

In [ ]:
xtrain